export const GET_COURSES = 'GET_COURSES';
export const GET_CATEGORY_COURSES = 'GET_CATEGORY_COURSES';
export const GET_COURSES_BY_CATEGORY = 'GET_COURSES_BY_CATEGORY';
export const GET_DETAILS_COURSES = 'GET_DETAILS_COURSES';
export const PAGINATION ='PAGINATION';