export const MenuItems = [
    {
        title:'Development',
        path:'/development',
        cName:'dropdown-link',
    },
    {
        title:'Design',
        path:'/development',
        cName:'dropdown-link',
    },
    {
        title:'Wordpress',
        path:'/development',
        cName:'dropdown-link',
    },
    {
        title:'Marketing',
        path:'/development',
        cName:'dropdown-link',
    },
]